eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
            defaultZone: http://localhost:8000/eureka/
    instance:
        hostname: localhost
#        leaseRenewalIntervalInSeconds: 1
#        leaseExpirationDurationInSeconds: 2 
    
server:
  port: 8020

spring:
  application:
    name: User-Service