server:
  port: 8030
  
spring:
  application:
    name: Note-Service

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost/8000/eureka
#  instance:
#    hostname: localhost

eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
            defaultZone: http://localhost:8000/eureka/

    instance:
        hostname: localhost

security:
  oauth2:
    client:
      clientId: 1530668643704380
      clientSecret: 649422e4c737a4eb6c8076abe27884c6
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

#security:
#    oauth2:
#        client:
#            clientId: 998699794694-cg43bj5llkkfcneh0m3183kju7huk75e.apps.googleusercontent.com
#            clientSecret: hMaFI5IOY3IsMf1tW4coB8sN
#            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#            tokenName: oauth_token
#            authenticationScheme: query
#            clientAuthenticationScheme: form
#            scope: profile
#        resource:
#            userInfoUri: https://www.googleapis.com/userinfo/v2/me
#            preferTokenInfo: false